### ISSUE TITLE
Cannot use pnpx shadcn ui?

### ISSUE THREAD

**Issue by Nevram30** [ahmad1702/shadcn-ui-cra#1]
I run an error that i cannot run pnpx this is the error message:

pnpx : The term 'pnpx' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the 
path is correct and try again.
At line:1 char:1
+ pnpx shadcn-ui add button
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (pnpx:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by ahmadaccino** [comment]
Hello,

This is an issue that is with shadcn-ui's cli tool specifically, and isn't a problem necessarily for this repo. [Here is an issue](https://github.com/shadcn-ui/ui/issues/648#issuecomment-1603234521) on the shadcn-ui repo that might fix you're issue, there were a couple of pnpx related issues on that repo as well that might resolve you're problem.
